name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.2
  - mlflow=2.3.0
  - pyyaml=6.0
  - hydra-core=1.3.2
  - pip=23.1.1
  - pip:
      - wandb==0.15.0
      - hydra-joblib-launcher==1.2.0