name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.1
  - pip=23.1.1
  - mlflow=2.3.0
  - scikit-learn=1.2.2
  - matplotlib=3.2.2
  - pillow=9.5.0
  - pip:
      - wandb==0.15.0